# Use an official Nginx image as a parent image
FROM nginx:alpine

# Copy the website files to the container
COPY ./public /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
